# create time
since: 2017

# header
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  Github: https://github.com/unclay

# Power by, Theme by, ICP Licensing
copyright: true
# ICP备案，前提需要开启copyright
ICP: 粤ICP备15064156号-1

# tongji.baidu.com
# baidu_analytics: a0cdc9f8d54a642c542084b55eaxxxxx
